#!/usr/bin/env python3
"""
Power Apps Controls JSON Generator
Generates proper Controls/*.json metadata files for Power Apps controls
"""

import json
from typing import Dict, List, Any

class ControlsJSONGenerator:
    """Generates Controls JSON metadata for Power Apps"""

    def __init__(self, start_unique_id: int = 7):
        self.current_unique_id = start_unique_id
        self.current_zindex = 1

    def get_next_id(self) -> str:
        """Get next unique control ID"""
        uid = str(self.current_unique_id)
        self.current_unique_id += 1
        return uid

    def get_next_zindex(self) -> int:
        """Get next Z-index"""
        z = self.current_zindex
        self.current_zindex += 1
        return z

    def create_property_rule(self, prop: str, script: str, category: str = "Design",
                            provider: str = "User") -> Dict:
        """Create a property rule"""
        return {
            "Property": prop,
            "Category": category,
            "InvariantScript": script,
            "RuleProviderType": provider
        }

    def create_property_state(self, prop: str, auto_binding: str = None) -> Any:
        """Create property state"""
        if auto_binding:
            return {
                "InvariantPropertyName": prop,
                "AutoRuleBindingEnabled": False,
                "AutoRuleBindingString": auto_binding,
                "NameMapSourceSchema": "?",
                "IsLockable": False,
                "AFDDataSourceName": ""
            }
        return prop

    def create_rectangle(self, name: str, parent: str, x: str, y: str, width: str,
                        height: str, fill: str = "RGBA(255, 255, 255, 1)",
                        border_thickness: str = "0", publish_order: int = 0) -> Dict:
        """Create Rectangle control JSON"""
        uid = self.get_next_id()
        zindex = self.get_next_zindex()

        return {
            "Type": "ControlInfo",
            "Name": name,
            "HasDynamicProperties": False,
            "Template": {
                "Id": "http://microsoft.com/appmagic/shapes/rectangle",
                "Version": "2.3.0",
                "LastModifiedTimestamp": "0",
                "Name": "rectangle",
                "FirstParty": True,
                "IsPremiumPcfControl": False,
                "IsCustomGroupControlTemplate": False,
                "CustomGroupControlTemplateName": "",
                "IsComponentDefinition": False,
                "OverridableProperties": {}
            },
            "Index": 0,
            "PublishOrderIndex": publish_order,
            "VariantName": "",
            "LayoutName": "",
            "MetaDataIDKey": "",
            "PersistMetaDataIDKey": False,
            "IsFromScreenLayout": False,
            "StyleName": "defaultRectangleStyle",
            "Parent": parent,
            "IsDataControl": False,
            "AllowAccessToGlobals": True,
            "OptimizeForDevices": "Off",
            "IsGroupControl": False,
            "IsAutoGenerated": False,
            "Rules": [
                self.create_property_rule("Fill", fill),
                self.create_property_rule("DisabledFill", "Self.Fill", provider="Unknown"),
                self.create_property_rule("PressedFill", "Self.Fill", provider="Unknown"),
                self.create_property_rule("HoverFill", "Self.Fill", provider="Unknown"),
                self.create_property_rule("BorderColor", "RGBA(0, 18, 107, 1)", provider="Unknown"),
                self.create_property_rule("BorderStyle", "BorderStyle.Solid", provider="Unknown"),
                self.create_property_rule("FocusedBorderColor", "Self.BorderColor", provider="Unknown"),
                self.create_property_rule("DisplayMode", "DisplayMode.Edit", provider="Unknown"),
                self.create_property_rule("X", x),
                self.create_property_rule("Y", y),
                self.create_property_rule("Width", width),
                self.create_property_rule("Height", height),
                self.create_property_rule("ZIndex", str(zindex), provider="Unknown"),
                self.create_property_rule("BorderThickness", border_thickness)
            ],
            "ControlPropertyState": [
                self.create_property_state("Fill", "RGBA(56, 96, 178, 1)"),
                "DisabledFill", "PressedFill", "HoverFill", "BorderColor", "BorderStyle",
                "FocusedBorderColor", "DisplayMode",
                self.create_property_state("X", "596"),
                self.create_property_state("Y", "16"),
                self.create_property_state("Width", "150"),
                self.create_property_state("Height", "100"),
                "ZIndex",
                self.create_property_state("BorderThickness", "0"),
                "FocusedBorderThickness"
            ],
            "IsLocked": False,
            "ControlUniqueId": uid,
            "Children": []
        }

    def create_label(self, name: str, parent: str, text: str, x: str, y: str,
                    width: str, height: str, color: str = "RGBA(0, 0, 0, 1)",
                    font: str = "Font.'Segoe UI'", size: str = "13",
                    align: str = "Align.Left", font_weight: str = "FontWeight.Normal",
                    publish_order: int = 0) -> Dict:
        """Create Label control JSON"""
        uid = self.get_next_id()
        zindex = self.get_next_zindex()

        return {
            "Type": "ControlInfo",
            "Name": name,
            "HasDynamicProperties": False,
            "Template": {
                "Id": "http://microsoft.com/appmagic/label",
                "Version": "2.5.1",
                "LastModifiedTimestamp": "0",
                "Name": "label",
                "FirstParty": True,
                "IsPremiumPcfControl": False,
                "IsCustomGroupControlTemplate": False,
                "CustomGroupControlTemplateName": "",
                "IsComponentDefinition": False,
                "OverridableProperties": {}
            },
            "Index": 0,
            "PublishOrderIndex": publish_order,
            "VariantName": "",
            "LayoutName": "",
            "MetaDataIDKey": "",
            "PersistMetaDataIDKey": False,
            "IsFromScreenLayout": False,
            "StyleName": "defaultLabelStyle",
            "Parent": parent,
            "IsDataControl": False,
            "AllowAccessToGlobals": True,
            "OptimizeForDevices": "Off",
            "IsGroupControl": False,
            "IsAutoGenerated": False,
            "Rules": [
                self.create_property_rule("Live", "Live.Off", "Data", "Unknown"),
                self.create_property_rule("Text", text, "Data"),
                self.create_property_rule("Role", "TextRole.Default", "Data", "Unknown"),
                self.create_property_rule("Overflow", "Overflow.Hidden", provider="Unknown"),
                self.create_property_rule("Color", color),
                self.create_property_rule("DisabledColor", "RGBA(166, 166, 166, 1)", provider="Unknown"),
                self.create_property_rule("PressedColor", "Self.Color", provider="Unknown"),
                self.create_property_rule("HoverColor", "Self.Color", provider="Unknown"),
                self.create_property_rule("BorderColor", "RGBA(0, 18, 107, 1)", provider="Unknown"),
                self.create_property_rule("DisabledBorderColor", "RGBA(56, 56, 56, 1)", provider="Unknown"),
                self.create_property_rule("PressedBorderColor", "Self.BorderColor", provider="Unknown"),
                self.create_property_rule("HoverBorderColor", "Self.BorderColor", provider="Unknown"),
                self.create_property_rule("BorderStyle", "BorderStyle.Solid", provider="Unknown"),
                self.create_property_rule("FocusedBorderColor", "Self.BorderColor", provider="Unknown"),
                self.create_property_rule("Fill", "RGBA(0, 0, 0, 0)", provider="Unknown"),
                self.create_property_rule("DisabledFill", "RGBA(0, 0, 0, 0)", provider="Unknown"),
                self.create_property_rule("PressedFill", "Self.Fill", provider="Unknown"),
                self.create_property_rule("HoverFill", "Self.Fill", provider="Unknown"),
                self.create_property_rule("Font", font),
                self.create_property_rule("FontWeight", font_weight),
                self.create_property_rule("Align", align),
                self.create_property_rule("VerticalAlign", "VerticalAlign.Middle", provider="Unknown"),
                self.create_property_rule("X", x),
                self.create_property_rule("Y", y),
                self.create_property_rule("Width", width),
                self.create_property_rule("Height", height),
                self.create_property_rule("DisplayMode", "DisplayMode.Edit", provider="Unknown"),
                self.create_property_rule("ZIndex", str(zindex), provider="Unknown"),
                self.create_property_rule("LineHeight", "1.2", provider="Unknown"),
                self.create_property_rule("BorderThickness", "0", provider="Unknown"),
                self.create_property_rule("FocusedBorderThickness", "0", provider="Unknown"),
                self.create_property_rule("Size", size),
                self.create_property_rule("Italic", "false", provider="Unknown"),
                self.create_property_rule("Underline", "false", provider="Unknown"),
                self.create_property_rule("Strikethrough", "false", provider="Unknown"),
                self.create_property_rule("PaddingTop", "5", provider="Unknown"),
                self.create_property_rule("PaddingRight", "5", provider="Unknown"),
                self.create_property_rule("PaddingBottom", "5", provider="Unknown"),
                self.create_property_rule("PaddingLeft", "5", provider="Unknown")
            ],
            "ControlPropertyState": [
                "Live", "Overflow",
                self.create_property_state("Text", "\"Text\""),
                "Role",
                self.create_property_state("Color", "RGBA(0, 0, 0, 1)"),
                "DisabledColor", "PressedColor", "HoverColor", "BorderColor",
                "DisabledBorderColor", "PressedBorderColor", "HoverBorderColor",
                "BorderStyle", "FocusedBorderColor", "Fill", "DisabledFill",
                "PressedFill", "HoverFill",
                self.create_property_state("Font", "Font.'Open Sans'"),
                self.create_property_state("FontWeight", "FontWeight.Normal"),
                self.create_property_state("Align", "Align.Left"),
                "VerticalAlign",
                self.create_property_state("X", "40"),
                self.create_property_state("Y", "40"),
                self.create_property_state("Width", "150"),
                self.create_property_state("Height", "40"),
                "DisplayMode", "ZIndex", "LineHeight", "BorderThickness",
                "FocusedBorderThickness",
                self.create_property_state("Size", "13"),
                "Italic", "Underline", "Strikethrough",
                "PaddingTop", "PaddingRight", "PaddingBottom", "PaddingLeft"
            ],
            "IsLocked": False,
            "ControlUniqueId": uid,
            "Children": []
        }

    def create_gallery(self, name: str, parent: str, items: str, x: str, y: str,
                      width: str, height: str, variant: str = "galleryVertical",
                      template_size: str = "100", template_padding: str = "5",
                      children: List[Dict] = None, publish_order: int = 0) -> Dict:
        """Create Gallery control JSON"""
        uid = self.get_next_id()
        zindex = self.get_next_zindex()

        gallery_id = "http://microsoft.com/appmagic/gallery"

        return {
            "Type": "ControlInfo",
            "Name": name,
            "HasDynamicProperties": False,
            "Template": {
                "Id": gallery_id,
                "Version": "2.5.1",
                "LastModifiedTimestamp": "0",
                "Name": "gallery",
                "FirstParty": True,
                "IsPremiumPcfControl": False,
                "IsCustomGroupControlTemplate": False,
                "CustomGroupControlTemplateName": "",
                "IsComponentDefinition": False,
                "OverridableProperties": {}
            },
            "Index": 0,
            "PublishOrderIndex": publish_order,
            "VariantName": variant,
            "LayoutName": "",
            "MetaDataIDKey": "",
            "PersistMetaDataIDKey": False,
            "IsFromScreenLayout": False,
            "StyleName": "defaultGalleryStyle",
            "Parent": parent,
            "IsDataControl": True,
            "AllowAccessToGlobals": True,
            "OptimizeForDevices": "Off",
            "IsGroupControl": False,
            "IsAutoGenerated": False,
            "Rules": [
                self.create_property_rule("Items", items, "Data"),
                self.create_property_rule("Layout", "Layout.Vertical", provider="Unknown"),
                self.create_property_rule("LoadingSpinner", "LoadingSpinner.None", provider="Unknown"),
                self.create_property_rule("LoadingSpinnerColor", "RGBA(56, 96, 178, 1)", provider="Unknown"),
                self.create_property_rule("BorderColor", "RGBA(0, 18, 107, 1)", provider="Unknown"),
                self.create_property_rule("BorderStyle", "BorderStyle.Solid", provider="Unknown"),
                self.create_property_rule("BorderThickness", "0", provider="Unknown"),
                self.create_property_rule("Fill", "RGBA(0, 0, 0, 0)", provider="Unknown"),
                self.create_property_rule("DisplayMode", "DisplayMode.Edit", provider="Unknown"),
                self.create_property_rule("X", x),
                self.create_property_rule("Y", y),
                self.create_property_rule("Width", width),
                self.create_property_rule("Height", height),
                self.create_property_rule("ZIndex", str(zindex), provider="Unknown"),
                self.create_property_rule("TemplateSize", template_size),
                self.create_property_rule("TemplatePadding", template_padding),
                self.create_property_rule("Transition", "Transition.None", provider="Unknown"),
                self.create_property_rule("ShowScrollbar", "true", provider="Unknown"),
                self.create_property_rule("WrapCount", "1", provider="Unknown")
            ],
            "ControlPropertyState": [
                self.create_property_state("Items", "CustomGallerySample"),
                "Layout", "LoadingSpinner", "LoadingSpinnerColor", "BorderColor",
                "BorderStyle", "BorderThickness", "Fill", "DisplayMode",
                self.create_property_state("X", "40"),
                self.create_property_state("Y", "40"),
                self.create_property_state("Width", "200"),
                self.create_property_state("Height", "300"),
                "ZIndex",
                self.create_property_state("TemplateSize", "100"),
                self.create_property_state("TemplatePadding", "0"),
                "Transition", "ShowScrollbar", "WrapCount"
            ],
            "IsLocked": False,
            "ControlUniqueId": uid,
            "Children": children if children else []
        }

    def create_button(self, name: str, parent: str, text: str, on_select: str,
                     x: str, y: str, width: str, height: str,
                     fill: str = "RGBA(56, 96, 178, 1)", size: str = "14",
                     font_weight: str = "FontWeight.Semibold",
                     publish_order: int = 0) -> Dict:
        """Create Button control JSON"""
        uid = self.get_next_id()
        zindex = self.get_next_zindex()

        return {
            "Type": "ControlInfo",
            "Name": name,
            "HasDynamicProperties": False,
            "Template": {
                "Id": "http://microsoft.com/appmagic/button",
                "Version": "2.3.0",
                "LastModifiedTimestamp": "0",
                "Name": "button",
                "FirstParty": True,
                "IsPremiumPcfControl": False,
                "IsCustomGroupControlTemplate": False,
                "CustomGroupControlTemplateName": "",
                "IsComponentDefinition": False,
                "OverridableProperties": {}
            },
            "Index": 0,
            "PublishOrderIndex": publish_order,
            "VariantName": "",
            "LayoutName": "",
            "MetaDataIDKey": "",
            "PersistMetaDataIDKey": False,
            "IsFromScreenLayout": False,
            "StyleName": "defaultButtonStyle",
            "Parent": parent,
            "IsDataControl": False,
            "AllowAccessToGlobals": True,
            "OptimizeForDevices": "Off",
            "IsGroupControl": False,
            "IsAutoGenerated": False,
            "Rules": [
                self.create_property_rule("OnSelect", on_select, "Behavior"),
                self.create_property_rule("Text", text, "Data"),
                self.create_property_rule("Fill", fill),
                self.create_property_rule("DisabledFill", "RGBA(244, 244, 244, 1)", provider="Unknown"),
                self.create_property_rule("PressedFill", "ColorFade(Self.Fill, -20%)", provider="Unknown"),
                self.create_property_rule("HoverFill", "ColorFade(Self.Fill, -10%)", provider="Unknown"),
                self.create_property_rule("Color", "RGBA(255, 255, 255, 1)", provider="Unknown"),
                self.create_property_rule("DisabledColor", "RGBA(166, 166, 166, 1)", provider="Unknown"),
                self.create_property_rule("PressedColor", "Self.Color", provider="Unknown"),
                self.create_property_rule("HoverColor", "Self.Color", provider="Unknown"),
                self.create_property_rule("BorderColor", "RGBA(0, 18, 107, 1)", provider="Unknown"),
                self.create_property_rule("DisabledBorderColor", "RGBA(56, 56, 56, 1)", provider="Unknown"),
                self.create_property_rule("PressedBorderColor", "Self.BorderColor", provider="Unknown"),
                self.create_property_rule("HoverBorderColor", "Self.BorderColor", provider="Unknown"),
                self.create_property_rule("BorderStyle", "BorderStyle.Solid", provider="Unknown"),
                self.create_property_rule("FocusedBorderColor", "Self.BorderColor", provider="Unknown"),
                self.create_property_rule("Font", "Font.'Segoe UI'", provider="Unknown"),
                self.create_property_rule("FontWeight", font_weight),
                self.create_property_rule("DisplayMode", "DisplayMode.Edit", provider="Unknown"),
                self.create_property_rule("X", x),
                self.create_property_rule("Y", y),
                self.create_property_rule("Width", width),
                self.create_property_rule("Height", height),
                self.create_property_rule("ZIndex", str(zindex), provider="Unknown"),
                self.create_property_rule("BorderThickness", "0", provider="Unknown"),
                self.create_property_rule("FocusedBorderThickness", "2", provider="Unknown"),
                self.create_property_rule("Size", size),
                self.create_property_rule("Italic", "false", provider="Unknown"),
                self.create_property_rule("Underline", "false", provider="Unknown"),
                self.create_property_rule("Strikethrough", "false", provider="Unknown"),
                self.create_property_rule("PaddingTop", "5", provider="Unknown"),
                self.create_property_rule("PaddingRight", "5", provider="Unknown"),
                self.create_property_rule("PaddingBottom", "5", provider="Unknown"),
                self.create_property_rule("PaddingLeft", "5", provider="Unknown"),
                self.create_property_rule("RadiusTopLeft", "5", provider="Unknown"),
                self.create_property_rule("RadiusTopRight", "5", provider="Unknown"),
                self.create_property_rule("RadiusBottomLeft", "5", provider="Unknown"),
                self.create_property_rule("RadiusBottomRight", "5", provider="Unknown")
            ],
            "ControlPropertyState": [
                self.create_property_state("OnSelect"),
                self.create_property_state("Text", "\"Button\""),
                self.create_property_state("Fill", "RGBA(56, 96, 178, 1)"),
                "DisabledFill", "PressedFill", "HoverFill", "Color", "DisabledColor",
                "PressedColor", "HoverColor", "BorderColor", "DisabledBorderColor",
                "PressedBorderColor", "HoverBorderColor", "BorderStyle",
                "FocusedBorderColor", "Font",
                self.create_property_state("FontWeight", "FontWeight.Semibold"),
                "DisplayMode",
                self.create_property_state("X", "40"),
                self.create_property_state("Y", "40"),
                self.create_property_state("Width", "150"),
                self.create_property_state("Height", "50"),
                "ZIndex", "BorderThickness", "FocusedBorderThickness",
                self.create_property_state("Size", "13"),
                "Italic", "Underline", "Strikethrough",
                "PaddingTop", "PaddingRight", "PaddingBottom", "PaddingLeft",
                "RadiusTopLeft", "RadiusTopRight", "RadiusBottomLeft", "RadiusBottomRight"
            ],
            "IsLocked": False,
            "ControlUniqueId": uid,
            "Children": []
        }
